apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
  labels:
    app: zitadel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zitadel
      version: v1
  template:
    metadata:
      labels:
        app: zitadel
        version: v1
    spec:
      containers:
      - name: zitadel
        image: darrylio/zitadel-nats-integration:1
        imagePullPolicy: IfNotPresent
        args: ["start"]
        ports:
        - name: grpc
          containerPort: 50001
        - name: http
          containerPort: 50002
        - name: ui
          containerPort: 50003
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          periodSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 5
          failureThreshold: 2
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CHAT_URL
          valueFrom:
            secretKeyRef:
              name: zitadel-secrets-vars
              key: ZITADEL_GOOGLE_CHAT_URL
        - name: TWILIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: zitadel-secrets-vars
              key: ZITADEL_TWILIO_AUTH_TOKEN
        - name: TWILIO_SERVICE_SID
          valueFrom:
            secretKeyRef:
              name: zitadel-secrets-vars
              key: ZITADEL_TWILIO_SID
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zitadel-secrets-vars
              key: ZITADEL_EMAILAPPKEY
        envFrom:
          - configMapRef:
              name: zitadel-vars
        volumeMounts:
          - name: zitadel-secret
            mountPath: /secret
          - name: console-config
            mountPath: /console/environment.json
            subPath: environment.json
      imagePullSecrets:
      - name: githubsecret
      volumes:
        - name: zitadel-secret
          secret:
            secretName: zitadel-secret
        - name: console-config
          configMap:
            name: console-config
